name: 'Push Docker GCR'
description: 'Push docker image to Google Container Registry'
branding:
  color: 'green'
  icon: 'box'
inputs:
  gcr_host:
    description: 'Google Container Registry Host'
    default: 'gcr.io'
  image_name:
    description: 'Docker Image Name'
    required: true
  image_tag:
    description: 'Docker Image Tag'
    required: true
  gcr_project_id:
    description: 'google project Id'
    required: true
  working_dir:
    description: 'the directory to look the docker file in'
    required: false
    default: '.'
runs:
  using: 'docker'
  image: 'Dockerfile'
